name: HPE ATLAS Day 16

on:
  push:
    branches:
      - main

jobs:
  hello:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Display Message
        run: echo "Welcome to HPE ATLAS Day 16"

      - name: Show Current Directory
        run: pwd

      - name: List Files
        run: ls -la
